# Generated by Django 4.0 on 2021-12-26 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_point_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='point',
            old_name='name',
            new_name='fullname',
        ),
    ]
