# Generated by Django 4.0 on 2021-12-26 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='map.category'),
            preserve_default=False,
        ),
    ]
